# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: kevingyang72@gmail.com
author_name: Kevin Yang
has_binder: false
has_settings: false
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extension.
python_name: myextension
repository: https://github.com/NEU-Coop-2024/syntax_highlighting
test: true

